differentialhq/differential

- ts-core/src/Differential.ts
`d.service` is omitting type information which result in no type checking for subsequent `d.call` and `d.background` functions.
Update `RegisteredService` type to be generic, allowing for more specific `ServiceDefinition`  information to be retained.
> Fix: Persist ServiceDefinition type information

- ts-core/src/Differential.ts
- ts-core/src/tests/monolith/monolith.test.ts
Adds a `buildClient()` function which produces a type-safe service client for easier ergonomics.
Usage:
```
const client = d.buildClient<typeof expertService>()
await client.callExpert("Can't touch this")
```
> Add service client builder

- changeset-builder/logs/ts-core.csv
- ts-core/src/Differential.ts
- ts-core/src/tests/monolith/monolith.test.ts
Add (currently unused) type-safe `service` param to `buildClient` to make service name available at runtime.
> fix: Enforce service name param

- docs/package.json
- package-lock.json
`npm install` is attempting to resolve the `@differentialhq/core` package from NPM rather than the local NPM `workspace`.
For what ever reason, the `package-lock.json` is [attempting to fetch](https://github.com/differentialhq/differential/actions/runs/7327195278/job/19953769912) a version which is not yet published (3.2.0) causing the pipeline to fail.
Pin `docs` `@differentialhq/core` dependency to the current version. This should be incremented automatically by `learna version`.
> fix: use workspace dependency rather than registry

- docs/api/index.md
Update [API docs](https://docs.differential.dev/api/) basic usage section to use client syntax
> docs: update api docs to use client syntax

- .github/workflows/test.yml
- control-plane/src/modules/contract.ts
- control-plane/src/modules/data.ts
- control-plane/src/modules/jobs.test.ts
- control-plane/src/modules/jobs.ts
- control-plane/src/modules/router.ts
- docs/package.json
- scripts/docs.sh
- ts-core/docs/classes/Differential.md
- ts-core/src/Differential.ts
- ts-core/src/contract.ts
Clients will now use the `<service>` parameter in `d.client<typeof myService>("<service>")` to create and pull jobs.
> fix: Shard jobs by the service name

- admin/app/clusters/[id]/DataTable.tsx
`noDataMessage` is not currently being rendered.
> fix: Render noDataMessage on cluster tables

- admin/app/clusters/[id]/LiveTables.tsx
- admin/client/contract.ts
- control-plane/src/modules/contract.ts
- control-plane/src/modules/management.ts
Renders execution time from #28 if available
> feat: Render execution time in admin

- control-plane/package.json
- control-plane/src/modules/contract.ts
- control-plane/src/modules/eventAggregation.test.ts
- control-plane/src/modules/eventAggregation.ts
- control-plane/src/modules/events.ts
- control-plane/src/modules/influx.ts
- control-plane/src/modules/jobs.ts
- control-plane/src/modules/router.ts
- package-lock.json
Implements event storage and aggregation with [InfluxDB](https://github.com/influxdata/influxdb) time series database.
- Introduces a `writeEvent` which will publish events using the [InfluxDB node client](https://github.com/influxdata/influxdb-client-js/) which will handle batching / background data writing
- Add events tracking for `jobCreated`, `jobResulted`, `machinePing`
- Creates some basic event aggregation queries for retrieving metrics
- Adds a `getFunctionMetrics` endpoint for retrieving request count and average execution time for a given time period
Please note: This PR should be safe to deploy _without_ provisioning any InfluxDB instance based on the [INFLUXDB_ENABLED](https://github.com/differentialhq/differential/blob/efea7b2eb62092c8591f53f81e2a1417514b7b34/control-plane/sr …
> feat: Initial service metrics with influx DB

- ts-core/src/Differential.ts
- ts-core/src/task-queue.test.ts
- ts-core/src/tests/e2ee/d.ts
- ts-core/src/tests/e2ee/e2ee.test.ts
- ts-core/src/tests/idempotency/d.ts
- ts-core/src/tests/idempotency/idempotency.test.ts
- ts-core/src/tests/monolith/d.ts
- ts-core/src/tests/monolith/monolith.test.ts
Expose the `getNextJobs` `ttl` param via a `jobPollWaitTime` configuration option on `Differential`.
This allows us to configure a lower `ttl` for test cases to **reduce** the likelihood of a dangling request from a previous test case consuming the job created in the next one.
> feat: Allow polling wait time configuration

- ts-core/src/Differential.ts
- ts-core/src/tests/monolith/monolith.test.ts
- Throw error when a service attempts to start again.
- Scope polling clients to `PollingAgent` and establish `AbortController`s.
- Refactor tests for stability
> fix: Improve polling and shutdown stability

- control-plane/src/modules/contract.ts
- control-plane/src/modules/events.ts
- control-plane/src/modules/router.ts
Adds a control plane endpoint for ingesting events from the client. This can be used for instrumenting function invocation latency, system resources, etc.
This endpoint simply forwards the events into `influxdb`. In the future, we may want to look at using the [influxdb node client](https://github.com/influxdata/influxdb-client-js/) on the client which will handle batching for us and reduce load on the control plane.
Will be followed by #69
> feat: Client metric ingestion endpoint

- package-lock.json
- ts-core/package.json
- ts-core/src/Differential.ts
- ts-core/src/contract.ts
- ts-core/src/events.test.ts
- ts-core/src/events.ts
Adds an `Event` class to the client which is responsible for batching and pushing events to the client metric ingestion endpoint defined in #68.
Also adds some initial events: 
- `machineResourceProbe` for instrumenting CPU / MEM usage
- `functionInvocation` for instrumenting round trip function time
This endpoint simply forwards the events into `influxdb`. In the future, we may want to look at using the [influxdb node client](https://github.com/influxdata/influxdb-client-js/) on the client which will handle batching for us and reduce load on the control plane.
> feat: Publish client metrics to control plane

- control-plane/src/modules/contract.ts
- control-plane/src/modules/event-aggregation.test.ts
- control-plane/src/modules/event-aggregation.ts
- control-plane/src/modules/router.ts
Makes a couple changes to the metrics query endpoint ahead of building some metric graphs.
Return metrics as time series array using `aggregateWindow` (currently hard coded to `1m`).
Allow the `functionName` and `serviceName` to be omitted from metric queries, allowing the same endpointy to be used.
Will be followed by initial UI changes in #72
> feat: Return metrics as time series array

- admin/app/clusters/[clusterId]/services/[serviceName]/ServiceMetrics.tsx
- admin/app/clusters/[clusterId]/services/[serviceName]/page.tsx
- admin/client/contract.ts
- admin/package.json
- control-plane/src/modules/contract.ts
- control-plane/src/modules/event-aggregation.test.ts
- control-plane/src/modules/event-aggregation.ts
- control-plane/src/modules/router.ts
- package-lock.json
Adds an initial graph of service calls based on the changes in #71  and using [Recharts](https://recharts.org/en-US/api).
Built into a new comment `ServiceMetrics` which will eventually house controls for filtering, etc.
> feat: Request count graph

- admin/app/clusters/[clusterId]/services/[serviceName]/ServiceMetrics.tsx
- admin/app/clusters/[clusterId]/services/[serviceName]/page.tsx
A couple small fixes for the metric graph view #72 
- Use [getToken()](https://clerk.com/docs/references/backend/sessions/get-token) to ensure the auth token remains fresh. Currently this expires after a couple retries.
- Hide graph if no data is available (in the future we can show a nicer placeholder but currently it just looks broken)
> fix: Use getToken for retrieving auth token

- control-plane/src/modules/contract.ts
- control-plane/src/modules/data.ts
- control-plane/src/modules/event-aggregation.test.ts
- control-plane/src/modules/event-aggregation.ts
- control-plane/src/modules/events.ts
- control-plane/src/modules/jobs.ts
- control-plane/src/modules/router.ts
This change exposes a `writeJobActivity` util which will send job based data into influxdb as a `_measurement="jobActivity"`. Plus, minor refactoring to bring all jobs module code into jobs.ts.
> feat: Write job activity to influxdb

- ts-core/src/Differential.test.ts
- ts-core/src/Differential.ts
This fixes a bug where client initialisation without the optional parameters results in an initialization error due to erroneous Typescript assertions.
> fix: Fix job poll timer initialization

- control-plane/package.json
- control-plane/src/modules/data.ts
- control-plane/src/modules/jobs.ts
- control-plane/src/modules/service-definitions.ts
- package-lock.json
- ts-core/src/functions.ts
Add caching to differential functions.
```ts
// src/services/product.ts
const getProduct = async (productId: string) => {
const product = await getProductFromDatabase(productId);
return product;
};
export const productService = d.service({
name: "product",
functions: {
getProduct: cached(getProduct, 10000), // cache results for 10 seconds
},
});
// src/client.ts
const productClient = d.client<typeof productService>("product");
const productId = "123";
const product = await productClient.getProduct(productId, {
$cacheKey: productId,
});
// if you call the function again with the same cache key, previous result will be returned
const product2 = await productClient.getProduct(productId, {
$cacheKey: productId,
});
assert.deepEqual(product === product2);
```
> feat: Add caching

- ts-core/src/Differential.ts
- ts-core/src/task-queue.test.ts
- ts-core/src/task-queue.ts
Due to a weakly-typed import, unregistered function errors are not serialised properly. This PR fixes it and types the import strongly.
> fix: Fix serializing unregistered function errors

- README.md
- control-plane/README.md
- control-plane/fly.toml
- docs/advanced/self-hosting.md
Adding a more comprehensive self-hosting guide and detailed steps to use fly compute and fly postgres.
> docs: Adding self-hosting guides

- control-plane/src/modules/jwt.test.ts
- control-plane/src/modules/jwt.ts
- control-plane/src/modules/management.ts
Introduces the ability to configure a `MANAGEMENT_SECRET` in the control plane for basic secret authentication, so self-hosting deployments can bypass Clerk.
> feat: Add management token for self hosting

- ts-core/src/tests/caching/caching.test.ts
Disable caching test until https://github.com/differentialhq/differential/issues/103 is fixed.
> chore: Disable caching test temporarily

- cli/src/client/contract.ts
- cli/src/commands/deploy.ts
- cli/src/lib/client.ts
- cli/src/lib/release.ts
- cli/src/lib/upload.ts
- control-plane/src/modules/deployment/deployment.ts
The `differential deploy` command will now call the `/release` endpoint after uploading a service assets.
Adds polling for deployment status,  this is currently a noop as the deployment state is moved as part of the `/release` call however that will be moved into a background process in the future.
> feat(cli): Release deployments

- control-plane/drizzle/0036_ambiguous_human_robot.sql
- control-plane/drizzle/meta/0036_snapshot.json
- control-plane/drizzle/meta/_journal.json
- control-plane/src/index.ts
- control-plane/src/modules/data.ts
- control-plane/src/modules/deployment/deployment-provider.ts
- control-plane/src/modules/deployment/deployment.test.ts
- control-plane/src/modules/deployment/deployment.ts
- control-plane/src/modules/deployment/lambda-provider.ts
- control-plane/src/modules/deployment/mock-deployment-provider.ts
- control-plane/src/modules/deployment/scheduler.ts
- control-plane/src/modules/jobs/create-job.ts
- control-plane/src/modules/router.ts
Adds initial deployment scheduling.
This PR adds a new scheduled job which periodically scans for "pending" jobs, and notifies the `DeploymentProvider` with the number of jobs and the number of running machines.
The `DeploymentProvider` is then responsible for making a determination around starting up new instances if necessary. Currently, this just starts an instance if none are running.
This is a naive approach, we will want to move this scheduling behaviour into a seperate service or at least introduce some locking so that only one instance of the control plane is handling scheduling at once.
There is also no mechanism for scaling down, as this is not necessary for `LambdaProvider` which will timeout on idle.
Please note: `deployment_id` is not currently being set on the `machines` …
> feat: Initial deployment scheduling

- control-plane/drizzle/0037_empty_molecule_man.sql
- control-plane/drizzle/meta/0037_snapshot.json
- control-plane/drizzle/meta/_journal.json
- control-plane/src/modules/contract.ts
- control-plane/src/modules/data.ts
- control-plane/src/modules/deployment/lambda-provider.ts
- control-plane/src/modules/jobs/jobs.ts
- control-plane/src/modules/jobs/persist-result.ts
- control-plane/src/modules/observability/events.ts
- control-plane/src/modules/router.ts
- ts-core/src/Differential.ts
- ts-core/src/contract.ts
- Add `x-deployment-id` header to `/jobs-request` requests.
- Attach `deployment_id` to `machines` and `events`
- Set `DIFFERENTIAL_DEPLOYMENT_ID` to Lambda runtime environment.
> feat: Attach deployment to machine and events

- cli/src/lib/package.ts
Because our [Lambda entrypoint](https://github.com/differentialhq/differential/blob/main/cli/src/lib/package.ts#L200) relies on importing a service entrypoint to start each invocation, we are running into an issue when Lambda is [reusing the execution environment](https://docs.aws.amazon.com/lambda/latest/operatorguide/execution-environment.html) as the imports are cached and the entrypoint is not run again.
This is a temporary fix as, Ideally we do want to leverage the pre-warmed execution environment but we may need to re-think _how_ we start the service. i.e perhaps we accept a path to a module that exports the service and the entrypoint is responsible for calling `.listen()`.
> fix: Clear CommonJS cache between invocations

- admin/app/cli-auth/page.tsx
- cli/package.json
- cli/src/commands/auth.ts
- cli/src/index.ts
- cli/src/lib/auth.ts
- package-lock.json
- `differential auth login` will start listening at port 9999 and open the browser
- FE has a new `cli-auth` route which redirects checks authentication and redirects to localhost
> feat: Add CLI auth flow

- cli/src/commands/deploy-create.ts
- cli/src/commands/deploy-info.ts
- cli/src/commands/deploy.ts
- cli/src/index.ts
- cli/src/lib/client.ts
- control-plane/src/modules/router.ts
- control-plane/src/modules/routing-helpers.ts
- Use management token from `differential auth login` for ts-rest client requests
- Move commands around `differential deploy / d create`
- Add `differential deploy info` command
- Return failures when management routes don't have access to a requested cluster
> feat(cli): Use management token for authentication

- cli/package.json
- cli/src/commands/clusters-create.ts
- cli/src/commands/clusters-info.ts
- cli/src/commands/clusters-list.ts
- cli/src/commands/clusters-open.ts
- cli/src/commands/clusters.ts
- cli/src/constants.ts
- cli/src/index.ts
- cli/src/lib/auth.ts
- cli/src/utils.ts
- package-lock.json
Adds cluster management commands `list`, `info`, `open`, `create`.
> feat(cli): Add cluster management commands

- cli/src/commands/deploy-create.ts
- cli/src/utils.ts
Allow an arbitrary service name to be entered as part of deployment creation.
> feat(cli): Allow arbitrary service name

- control-plane/drizzle/0039_puzzling_vampiro.sql
- control-plane/drizzle/0040_mean_jazinda.sql
- control-plane/drizzle/0041_youthful_steve_rogers.sql
- control-plane/drizzle/meta/0039_snapshot.json
- control-plane/drizzle/meta/0040_snapshot.json
- control-plane/drizzle/meta/0041_snapshot.json
- control-plane/drizzle/meta/_journal.json
- control-plane/src/modules/cluster.ts
- control-plane/src/modules/data.ts
- control-plane/src/modules/jobs.test.ts
- control-plane/src/modules/jobs/create-job.ts
- control-plane/src/modules/jobs/jobs.ts
- control-plane/src/modules/jobs/persist-result.ts
- control-plane/src/modules/observability/events.ts
- ts-core/src/task-queue.ts
- Introduce `retry_on_stall_enabled` as a default=true at cluster level.
- Introduce a machine status `active` or `inactive`, which corresponds to `last_ping_time`.
- Fix a bug where `machine_id` was considered globally unique. Now it's scoped to a cluster.
- Write cluster events when machines stall.
> fix: Auto-retry jobs when machine stalls

- admin/app/cli-auth/page.tsx
Passes the [Clerk getToken()](https://clerk.com/docs/references/backend/sessions/get-token#get-token) call a reference to a custom template `extended-cli-token`
> feat: Extended CLI token

- cli/src/client/contract.ts
- cli/src/commands/client-lib-publish.ts
- cli/src/commands/deploy-create.ts
- cli/src/lib/package.ts
- cli/src/lib/upload.ts
- control-plane/drizzle/0043_closed_weapon_omega.sql
- control-plane/drizzle/meta/0043_snapshot.json
- control-plane/drizzle/meta/_journal.json
- control-plane/src/modules/assets.test.ts
- control-plane/src/modules/assets.ts
- control-plane/src/modules/contract.ts
- control-plane/src/modules/data.ts
- control-plane/src/modules/deployment/deployment.test.ts
- control-plane/src/modules/deployment/deployment.ts
- control-plane/src/modules/router.ts
Refactors the asset upload behaviour to be common between client library and service bundle uploads.
A new endpoint, `createAsset` been introduced which accepts a `target` (either a `deployment` or `client_library_versions`) and will return a pre-signed S3 URL for uploading an asset.
The CLI can now share the same upload behaviour _regardless_ of the target type, making it easier to introduce additional uploads in the future.
Also:
- Creates a new table `client_library_versions` to track client version uploads.
- The CLI `client publish` command now provides the option to upload a client library to `npm`
> feat: Cleanup asset upload behaviour

- .github/workflows/test.yml
Add `pull_request_target` which allows access to secrets for incoming PRs.
> chore: Use pull_request_target to build PRs

- control-plane/src/modules/cluster.ts
- control-plane/src/modules/deployment/deployment.test.ts
- control-plane/src/modules/deployment/deployment.ts
- control-plane/src/modules/deployment/lambda-provider.ts
- ts-core/src/Differential.test.ts
- ts-core/src/Differential.ts
- Inject API Secret into Lambda deployments.
- Update `Differential` to fallback to `process.env.DIFFERENTIAL_API_SECRET`
> feat: Inject API secret into deployments

- control-plane/src/modules/jobs/jobs.ts
The build started failing as `getJobStatuses` was returning `string` for `status` and `result_type` which did not confirm to the ts-rest contract.
Update the return type information.
> fix: Infer getJobStatuses return type

- cli/src/commands/client-lib-publish.ts
- cli/src/commands/deploy-create.ts
- cli/src/lib/client.ts
- control-plane/package.json
- control-plane/src/modules/contract.ts
- control-plane/src/modules/deployment/cfn-manager.test.ts
- control-plane/src/modules/deployment/cfn-manager.ts
- control-plane/src/modules/deployment/deployment-provider.ts
- control-plane/src/modules/deployment/deployment.ts
- control-plane/src/modules/deployment/lambda-cfn-provider.ts
- control-plane/src/modules/router.ts
- control-plane/src/modules/sns.test.ts
- control-plane/src/modules/sns.ts
- infrastructure/README.md
- infrastructure/cfn.yaml
- infrastructure/deployment/lambda-cfn.yaml
- package-lock.json
Replace CloudFormation stack update polling with [SNS events](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-topic.html).
- Adds an `/events/sns` endpoint for ingesting SNS events and updating our deployment state
- `infrastructure/cfn.yaml` provisions an SNS topic / subscription for delivering events to the control-plane
- CloudFormation requests will now specify an SNS topic for delivering update events
- CloudFormation requests will specify a `ClientRequestToken` (the `deploymentId`) for routing events to the correct deployment
https://github.com/differentialhq/differential/assets/9162298/6fde7b2f-72d0-4943-b770-9c2b64b14265
> feat: Update CloudFormation deployments based on SNS

- ts-core/src/results-poller.ts
- ts-core/src/tests/monolith/monolith.test.ts
`ResultsPoller` can be blocked waiting for a slow job to resolve.
This is particularly the case in the service to service test which is currently taking ~25 seconds.
When adding a new job to `ResultsPoller`, check that the job has been attempted after `FORCE_POLL_DELAY` and trigger a forced poll if not.
My testing locally sees the problematic test time reduce from 25s -> 5s.
> feat: Add FORCE_POLL_DELAY to ResultsPoller

- ts-core/src/results-poller.ts
Sometimes, two polling cycles may race to update the result. In this case, we just need to ignore the second attempt since the first attempt would have returned the result back.
> fix: Fix polling cycle race condition

- control-plane/src/index.ts
- control-plane/src/utilities/logger.ts
- Wraps requests in logger context with `path` and `requestId`
- Use `simple` log formatting in production
> feat: Wrap requests in logger context

- control-plane/drizzle/0047_certain_penance.sql
- control-plane/drizzle/meta/0047_snapshot.json
- control-plane/drizzle/meta/_journal.json
- control-plane/src/modules/data.ts
- control-plane/src/modules/deployment/deployment.test.ts
- control-plane/src/modules/deployment/deployment.ts
- control-plane/src/utilities/env.ts
Currently, an existing deployment will be marked as "inactive" as soon as `releaseDeployment` is called.
However, the new deployment may take some time to complete or may fail.
Defer making existing deployment as "inactive", until the new deployment is marked "active".
In the case of `lambda`, this is in response to a CloudFormation update via SNS.
> feat: Defer deployment inactivation

- control-plane/src/modules/jobs/jobs.test.ts
- control-plane/src/modules/jobs/persist-result.test.ts
- control-plane/src/modules/jobs/persist-result.ts
- control-plane/src/modules/observability/events.ts
- control-plane/src/utilities/errors.ts
When persisting results, control-plane should only accept the result if it was issued from the machine that last accepted the job. If not, it makes it possible for sessions marked as stalled to update the job status.
> fix: Persist result should respect the machine id

- control-plane/src/modules/deployment/cfn-manager.ts
- control-plane/src/utilities/env.ts
- docs/advanced/self-hosting.md
- infrastructure/cfn.yaml
Refactor the IAM permissions to use a [CloudFormation service role](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-iam-servicerole.html) for managing resources rather than providing the privileges directly to `ControlPlaneUser`
> feat: Refactor IAM to use CF Service Role

- .github/workflows/test.yml
- control-plane/tsconfig.json
Explicitly include `agent.ts` so it is included in `tsc` output.
> fix: Explicitly include agent source in build
