- admin/client/contract.ts
- ts-core/src/Differential.ts
- ts-core/src/contract.ts
- ts-core/src/task-queue.test.ts
- ts-core/src/task-queue.ts
Updates `ts-client` to record function execution time (requires changes in #28)
> feat: Record function execution time

- control-plane/package.json
- control-plane/src/modules/contract.ts
- control-plane/src/modules/cron.ts
- control-plane/src/modules/data.ts
- control-plane/src/modules/jobs.test.ts
- control-plane/src/modules/jobs.ts
- control-plane/src/modules/router.ts
- package-lock.json
This PR reduces the strain on the database by increasing the intervals for polling for DB and reduces the number of connection by increasing the long polling timeouts. Also, the control plane now considers the database liveness for a liveness check.
> feat: Longer and configurable long polling intervals

- docs/advanced/advanced-usage.md
- ts-core/src/functions.ts
Change the examples to be more relatable, and add the "Advanced Usage" docs.
> fix: Fix documentation on idempotency

- .github/workflows/test-and-docs.yml
- .github/workflows/test.yml
- Per build API secrets to avoid race conditions in tests
> chore: Per build API secrets

- control-plane/package.json
- control-plane/src/utilities/profiling.ts
- package-lock.json
- Adds sentry profiling based on the presence of a DSN
- Minor package updates
> chore: Adding Sentry profiling

- admin/app/clusters/[clusterId]/ClusterLiveTables.tsx
- admin/app/clusters/[clusterId]/helpers.tsx
- admin/app/clusters/[clusterId]/services/ServiceSummary.tsx
- admin/app/clusters/[clusterId]/services/[serviceName]/ServiceLiveTables.tsx
- admin/client/contract.ts
- admin/components/ui/DataTable.tsx
- admin/components/ui/badge.tsx
- admin/components/ui/scroll-area.tsx
- admin/package.json
- control-plane/src/modules/contract.ts
- control-plane/src/modules/events.ts
- control-plane/src/modules/jobs.ts
- control-plane/src/modules/management.ts
- control-plane/src/modules/router.ts
- control-plane/src/utilities/errors.ts
- package-lock.json
- ts-core/src/contract.ts
Admin Console changed to include live function calls and the service page changed to include a more detailed account of the historic calls.
> feat: Adding cluster activity

- LICENSE
With feedback from the open-source community the license is changed to Apache 2.0 which will make it much more friendlier to self-host.
Closes #39
> chore: Change license to Apache 2.0

- admin/app/clusters/[clusterId]/services/[serviceName]/ServiceMetrics.tsx
Render failure rate for request count
> feat: Render failure rate for request count

- admin/app/clusters/[clusterId]/services/[serviceName]/ServiceMetrics.tsx
- control-plane/src/modules/event-aggregation.ts
- Display the average function execution time, broken down by success / failure.
- Break up the event aggregation queries into reusable functions
> feat: Display average execution

- admin/app/clusters/[clusterId]/ClusterLiveTables.tsx
- admin/app/clusters/[clusterId]/activity/page.tsx
- admin/app/clusters/[clusterId]/page.tsx
- admin/app/clusters/[clusterId]/services/[serviceName]/ServiceLiveTables.tsx
- admin/client/contract.ts
- admin/components/composite/activity.tsx
- admin/components/ui/collapsible.tsx
- admin/components/ui/drawer.tsx
- admin/package.json
- control-plane/src/modules/contract.ts
- control-plane/src/modules/event-aggregation.test.ts
- control-plane/src/modules/event-aggregation.ts
- control-plane/src/modules/router.ts
- package-lock.json
Adding an activity log for the job for end to end telemetry for a specific `jobId`.
> feat: Activity log for jobs

- docs/getting-started/quick-start.md
Fix as per https://github.com/differentialhq/app/pull/2
> docs: Fix the docs for new examples

- admin/app/clusters/[clusterId]/ClusterLiveTables.tsx
- admin/app/clusters/[clusterId]/helpers.tsx
- admin/app/clusters/[clusterId]/services/ServiceSummary.tsx
Minor styling updates to the admin console.
> fix: Minor styling updates

- README.md
- docs/index.md
- Mark caching as done in the README.
- Update the docs homepage copy to be in line with the README.
> docs: Update caching documentation and docs homepage

- admin/client/contract.ts
- control-plane/src/modules/contract.ts
- ts-core/src/Differential.ts
- ts-core/src/contract.ts
- ts-core/src/functions.ts
Adds `retryable` function decorator for retrying functions on job stalling.
> feat: Adding the retryable function decorator

- control-plane/src/modules/observability/events.ts
Due to https://github.com/drizzle-team/drizzle-orm/issues/1061 the events lose the ms precision on the timestamp. This PR converts the query to a raw query, so the precision is preserved.
> fix: Convert writing events to a raw query

- ts-core/src/Differential.ts
In rare cases when the control-plane is unresponsive, the client may repeatedly poll exhausting event listeners. This change throttles the polling call, so it'll poll at most once every 2 seconds.
It also aborts polling if there are too many consecutive errors on polling.
> fix: Throttle polling to recover from server failures

- control-plane/drizzle/0033_high_komodo.sql
- control-plane/drizzle/meta/0033_snapshot.json
- control-plane/drizzle/meta/_journal.json
- control-plane/src/modules/data.ts
- control-plane/src/modules/predictor/client.ts
- control-plane/src/modules/predictor/contract.ts
This sets up the client and the database changes for adding predictive retries.
> chore: Setting up infrastructure for predictive retries

- control-plane/package.json
- control-plane/src/modules/deployment/deployment.ts
- control-plane/src/modules/deployment/lambda-provider.ts
- package-lock.json
Implements a `DeploymentProvider` #105 for Lambda and makes it the default.
> feat: Initial LambdaProvider

- control-plane/src/modules/deployment/lambda-provider.ts
- ts-core/src/Differential.ts
Adds a `maxIdleCycles` option to `PollingAgent` which is set with the `DIFFERNTIAL_DEPLOYMENT_PROVIDER` environment variable is set.
> feat: Add maxIdleCycles to shut down lambdas when inactive

- control-plane/package.json
- control-plane/src/modules/cron.ts
- control-plane/src/modules/deployment/scheduler.ts
- control-plane/src/modules/jobs/jobs.ts
- control-plane/src/modules/lock.ts
- package-lock.json
Introduce mutexes via postgres advisory locks.
> fix: Adding advisory locks to cron

- cli/package.json
- package-lock.json
- [detective](https://github.com/browserify/detective) was incorrectly installed as a `devDependency`
> fix(cli): move detective to dependency

- control-plane/src/modules/deployment/lambda-provider.ts
- [Disable lambda event reties](https://docs.aws.amazon.com/lambda/latest/dg/invocation-retries.html) as this would lead to additional, unintentional invocations.
- Update all "mutating" calls to lambda to retry if `ResourceConflictException` is returned.
> feat: disable lambda retries

- cli/src/client/contract.ts
- cli/src/commands/clusters-open.ts
- cli/src/commands/deploy-create.ts
- cli/src/commands/deploy-list.ts
- cli/src/commands/deploy.ts
- cli/src/constants.ts
- cli/src/lib/auth.ts
- cli/src/lib/client.ts
- cli/src/utils.ts
- control-plane/src/modules/contract.ts
- control-plane/src/modules/deployment/deployment.ts
- control-plane/src/modules/router.ts
Allow listing deployments via the CLI
- Create empty service on deployment
> feat(cli): Deployment list command

- control-plane/fly.toml
- control-plane/package.json
- control-plane/src/index.ts
- control-plane/src/modules/observability/events.ts
- package-lock.json
Expose internal metrics to the [fly.io prometheus instance](https://fly.io/docs/reference/metrics/)
> feat: Expose internal metrics to prometheus

- admin/app/clusters/[clusterId]/advanced/page.tsx
- admin/client/contract.ts
- cli/src/client/contract.ts
- cli/src/commands/client-lib-publish.ts
- cli/src/commands/deploy-create.ts
- cli/src/commands/deploy-info.ts
- cli/src/commands/deploy-list.ts
- cli/src/lib/auth.ts
- control-plane/src/modules/cluster.ts
- control-plane/src/modules/contract.ts
- control-plane/src/modules/management.test.ts
- control-plane/src/modules/management.ts
- control-plane/src/modules/router.ts
Gates Differential Cloud features (including package publishing) and present a waitlist prompt
> feat: Gate cloud features

- control-plane/src/modules/deployment/lambda-provider.ts
- docs/advanced/self-hosting.md
- infrastructure/README.md
- infrastructure/cfn.yaml
- Add CloudFormation template for `control-plane` access to AWS (S3, Lambda, etc)
- Add details to self-hosting docs
> docs: Add CloudFormation template

- admin/app/clusters/[clusterId]/helpers.tsx
- admin/app/clusters/[clusterId]/overview/page.tsx
- admin/app/clusters/[clusterId]/services/[serviceName]/ServiceDeployments.tsx
- admin/app/clusters/[clusterId]/services/[serviceName]/page.tsx
- admin/client/contract.ts
- control-plane/src/modules/contract.ts
- control-plane/src/modules/deployment/deployment.ts
- control-plane/src/modules/management.ts
- Add deployment list to admin service view
- Add Deployment count to admin cluster view
> feat(admin): Render deployment details

- docs/advanced/arguments-and-return-values.md
- docs/advanced/limitations.md
- ts-core/src/Differential.ts
- ts-core/src/errors.ts
- ts-core/src/serialize.test.ts
- ts-core/src/serialize.ts
- ts-core/src/types.ts
- Elaborate on arguments and return value limitations on serialisation
- Enforce runtime checks on serialization
- More tests on `serialize()`
> docs: Arguments and return values

- ts-core/package.json
- Correct [testTimeout jest configuration](https://jestjs.io/docs/configuration#testtimeout-number)
> fix: Resolve test warnings

- .github/workflows/docs-and-deploy.yml
- .github/workflows/test.yml
- ts-core/src/tests/monolith/monolith.test.ts
- Run test using `pull_request` to ensure they run again the `HEAD` of the PR's branch
- Share tests workflow between PR and main branch
- Make Docs and Deploy workflow dependent on successful test run
> chore: Github action updates

- control-plane/drizzle/0046_needy_brood.sql
- control-plane/drizzle/meta/0046_snapshot.json
- control-plane/drizzle/meta/_journal.json
- control-plane/src/modules/data.ts
- control-plane/src/modules/predictor/predictor.test.ts
- control-plane/src/modules/predictor/predictor.ts
- docs/advanced/predictive-retries.md
- Cache predictions for observability and cost reductions
- Expand on the docs on probabilistic behaviour
> fix: Cache predictive retries and better docs

- admin/app/clusters/[clusterId]/ClusterSettings.tsx
- admin/app/clusters/[clusterId]/activity/deployment/page.tsx
- admin/app/clusters/[clusterId]/monitoring/page.tsx
- admin/app/clusters/[clusterId]/services/[serviceName]/ServiceDeployments.tsx
- admin/client/contract.ts
- admin/components/composite/activity.tsx
- control-plane/src/modules/contract.ts
- control-plane/src/modules/deployment/deployment.ts
- control-plane/src/modules/deployment/scheduler.ts
- control-plane/src/modules/management.ts
- control-plane/src/modules/observability/event-aggregation.ts
- control-plane/src/modules/observability/events.ts
- control-plane/src/modules/router.ts
Adds events to track a deployments lifecycle and render these in the admin console.
> feat: Deployment event tracking

- admin/app/clusters/[clusterId]/Navigation.tsx
- admin/app/clusters/[clusterId]/advanced/page.tsx
- admin/app/clusters/[clusterId]/overview/ActivityChart.tsx
- admin/app/clusters/[clusterId]/overview/page.tsx
- admin/app/clusters/[clusterId]/services/[serviceName]/ServiceLiveTables.tsx
- admin/app/clusters/[clusterId]/services/[serviceName]/ServiceMetrics.tsx
- admin/app/clusters/[clusterId]/services/[serviceName]/page.tsx
- admin/app/clusters/fill-dates.ts
- control-plane/src/modules/management.ts
- Minor UI updates
- Cluster-wide activity chart
- Fix X axis on date charts
> feat: Better charts for services

- admin/app/clusters/[clusterId]/Navigation.tsx
- admin/app/clusters/[clusterId]/activity/page.tsx
- admin/app/clusters/[clusterId]/monitoring/page.tsx
- admin/app/clusters/[clusterId]/overview/ActivityChart.tsx
- admin/app/clusters/fill-dates.ts
- admin/components/composite/activity.tsx
- control-plane/src/modules/jobs/create-job.ts
- control-plane/src/modules/observability/events.ts
- Hide advanced settings
- Fix layouts
- Persist call config on events
- Make calls in the monitoring page clickable
> fix: Minor fixes to admin console

- cli/package.json
- cli/src/commands/repl.ts
- cli/src/index.ts
- package-lock.json
Adds a REPL session command to the CLI for development and testing.
https://github.com/differentialhq/differential/assets/9162298/4971c89c-74d4-432a-be3f-ee3d983fafbd
> feat(cli): REPL interface

- cli/src/client/contract.ts
- cli/src/commands/deploy-logs.ts
- cli/src/commands/deploy.ts
- cli/src/commands/repl.ts
- cli/src/utils.ts
- control-plane/package.json
- control-plane/src/modules/contract.ts
- control-plane/src/modules/deployment/deployment-provider.ts
- control-plane/src/modules/deployment/deployment.test.ts
- control-plane/src/modules/deployment/deployment.ts
- control-plane/src/modules/deployment/lambda-cfn-provider.ts
- control-plane/src/modules/deployment/mock-deployment-provider.ts
- control-plane/src/modules/router.ts
- package-lock.json
Initial deployment log fetching from CloudWatch and rendering via the CLI.
Currently just fetches the last 500 logs.
Will follow up with pagination and filtering.
> feat: Initial deployment log rendering

- cli/src/client/contract.ts
- cli/src/commands/deploy-logs.ts
- control-plane/src/modules/contract.ts
- control-plane/src/modules/deployment/deployment-provider.ts
- control-plane/src/modules/deployment/deployment.ts
- control-plane/src/modules/deployment/lambda-cfn-provider.ts
- control-plane/src/modules/router.ts
Adds the ability to fetch deployment logs within a selected time period
> feat: Add time selection to log query

- cli/src/client/contract.ts
- cli/src/commands/deploy-logs.ts
- control-plane/src/modules/contract.ts
- control-plane/src/modules/deployment/deployment-provider.ts
- control-plane/src/modules/deployment/deployment.ts
- control-plane/src/modules/deployment/lambda-cfn-provider.ts
- control-plane/src/modules/router.ts
Adds `--filter` option to CLI for filtering logs
> feat: Add log filtering option
